/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularioRouteImport } from './routes/vocabulario'
import { Route as RelatosRouteImport } from './routes/relatos'
import { Route as PalabraDelDiaRouteImport } from './routes/palabra-del-dia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JuegosRouteImport } from './routes/juegos'
import { Route as EscuchaRouteImport } from './routes/escucha'
import { Route as DiccionarioRouteImport } from './routes/diccionario'
import { Route as CulturaRouteImport } from './routes/cultura'
import { Route as ContribuirRouteImport } from './routes/contribuir'
import { Route as AprendeRouteImport } from './routes/aprende'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JuegosIndexRouteImport } from './routes/juegos.index'
import { Route as JuegosSopaRouteImport } from './routes/juegos.sopa'
import { Route as JuegosQuizRouteImport } from './routes/juegos.quiz'
import { Route as JuegosMemoramaRouteImport } from './routes/juegos.memorama'
import { Route as JuegosFlasgcardsRouteImport } from './routes/juegos.flasgcards'
import { Route as AprendeSlugRouteImport } from './routes/aprende.$slug'

const VocabularioRoute = VocabularioRouteImport.update({
  id: '/vocabulario',
  path: '/vocabulario',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatosRoute = RelatosRouteImport.update({
  id: '/relatos',
  path: '/relatos',
  getParentRoute: () => rootRouteImport,
} as any)
const PalabraDelDiaRoute = PalabraDelDiaRouteImport.update({
  id: '/palabra-del-dia',
  path: '/palabra-del-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosRoute = JuegosRouteImport.update({
  id: '/juegos',
  path: '/juegos',
  getParentRoute: () => rootRouteImport,
} as any)
const EscuchaRoute = EscuchaRouteImport.update({
  id: '/escucha',
  path: '/escucha',
  getParentRoute: () => rootRouteImport,
} as any)
const DiccionarioRoute = DiccionarioRouteImport.update({
  id: '/diccionario',
  path: '/diccionario',
  getParentRoute: () => rootRouteImport,
} as any)
const CulturaRoute = CulturaRouteImport.update({
  id: '/cultura',
  path: '/cultura',
  getParentRoute: () => rootRouteImport,
} as any)
const ContribuirRoute = ContribuirRouteImport.update({
  id: '/contribuir',
  path: '/contribuir',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendeRoute = AprendeRouteImport.update({
  id: '/aprende',
  path: '/aprende',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosIndexRoute = JuegosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JuegosRoute,
} as any)
const JuegosSopaRoute = JuegosSopaRouteImport.update({
  id: '/sopa',
  path: '/sopa',
  getParentRoute: () => JuegosRoute,
} as any)
const JuegosQuizRoute = JuegosQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => JuegosRoute,
} as any)
const JuegosMemoramaRoute = JuegosMemoramaRouteImport.update({
  id: '/memorama',
  path: '/memorama',
  getParentRoute: () => JuegosRoute,
} as any)
const JuegosFlasgcardsRoute = JuegosFlasgcardsRouteImport.update({
  id: '/flasgcards',
  path: '/flasgcards',
  getParentRoute: () => JuegosRoute,
} as any)
const AprendeSlugRoute = AprendeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AprendeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprende': typeof AprendeRouteWithChildren
  '/contribuir': typeof ContribuirRoute
  '/cultura': typeof CulturaRoute
  '/diccionario': typeof DiccionarioRoute
  '/escucha': typeof EscuchaRoute
  '/juegos': typeof JuegosRouteWithChildren
  '/login': typeof LoginRoute
  '/palabra-del-dia': typeof PalabraDelDiaRoute
  '/relatos': typeof RelatosRoute
  '/vocabulario': typeof VocabularioRoute
  '/aprende/$slug': typeof AprendeSlugRoute
  '/juegos/flasgcards': typeof JuegosFlasgcardsRoute
  '/juegos/memorama': typeof JuegosMemoramaRoute
  '/juegos/quiz': typeof JuegosQuizRoute
  '/juegos/sopa': typeof JuegosSopaRoute
  '/juegos/': typeof JuegosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprende': typeof AprendeRouteWithChildren
  '/contribuir': typeof ContribuirRoute
  '/cultura': typeof CulturaRoute
  '/diccionario': typeof DiccionarioRoute
  '/escucha': typeof EscuchaRoute
  '/login': typeof LoginRoute
  '/palabra-del-dia': typeof PalabraDelDiaRoute
  '/relatos': typeof RelatosRoute
  '/vocabulario': typeof VocabularioRoute
  '/aprende/$slug': typeof AprendeSlugRoute
  '/juegos/flasgcards': typeof JuegosFlasgcardsRoute
  '/juegos/memorama': typeof JuegosMemoramaRoute
  '/juegos/quiz': typeof JuegosQuizRoute
  '/juegos/sopa': typeof JuegosSopaRoute
  '/juegos': typeof JuegosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprende': typeof AprendeRouteWithChildren
  '/contribuir': typeof ContribuirRoute
  '/cultura': typeof CulturaRoute
  '/diccionario': typeof DiccionarioRoute
  '/escucha': typeof EscuchaRoute
  '/juegos': typeof JuegosRouteWithChildren
  '/login': typeof LoginRoute
  '/palabra-del-dia': typeof PalabraDelDiaRoute
  '/relatos': typeof RelatosRoute
  '/vocabulario': typeof VocabularioRoute
  '/aprende/$slug': typeof AprendeSlugRoute
  '/juegos/flasgcards': typeof JuegosFlasgcardsRoute
  '/juegos/memorama': typeof JuegosMemoramaRoute
  '/juegos/quiz': typeof JuegosQuizRoute
  '/juegos/sopa': typeof JuegosSopaRoute
  '/juegos/': typeof JuegosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprende'
    | '/contribuir'
    | '/cultura'
    | '/diccionario'
    | '/escucha'
    | '/juegos'
    | '/login'
    | '/palabra-del-dia'
    | '/relatos'
    | '/vocabulario'
    | '/aprende/$slug'
    | '/juegos/flasgcards'
    | '/juegos/memorama'
    | '/juegos/quiz'
    | '/juegos/sopa'
    | '/juegos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprende'
    | '/contribuir'
    | '/cultura'
    | '/diccionario'
    | '/escucha'
    | '/login'
    | '/palabra-del-dia'
    | '/relatos'
    | '/vocabulario'
    | '/aprende/$slug'
    | '/juegos/flasgcards'
    | '/juegos/memorama'
    | '/juegos/quiz'
    | '/juegos/sopa'
    | '/juegos'
  id:
    | '__root__'
    | '/'
    | '/aprende'
    | '/contribuir'
    | '/cultura'
    | '/diccionario'
    | '/escucha'
    | '/juegos'
    | '/login'
    | '/palabra-del-dia'
    | '/relatos'
    | '/vocabulario'
    | '/aprende/$slug'
    | '/juegos/flasgcards'
    | '/juegos/memorama'
    | '/juegos/quiz'
    | '/juegos/sopa'
    | '/juegos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprendeRoute: typeof AprendeRouteWithChildren
  ContribuirRoute: typeof ContribuirRoute
  CulturaRoute: typeof CulturaRoute
  DiccionarioRoute: typeof DiccionarioRoute
  EscuchaRoute: typeof EscuchaRoute
  JuegosRoute: typeof JuegosRouteWithChildren
  LoginRoute: typeof LoginRoute
  PalabraDelDiaRoute: typeof PalabraDelDiaRoute
  RelatosRoute: typeof RelatosRoute
  VocabularioRoute: typeof VocabularioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulario': {
      id: '/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof VocabularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatos': {
      id: '/relatos'
      path: '/relatos'
      fullPath: '/relatos'
      preLoaderRoute: typeof RelatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palabra-del-dia': {
      id: '/palabra-del-dia'
      path: '/palabra-del-dia'
      fullPath: '/palabra-del-dia'
      preLoaderRoute: typeof PalabraDelDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos': {
      id: '/juegos'
      path: '/juegos'
      fullPath: '/juegos'
      preLoaderRoute: typeof JuegosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escucha': {
      id: '/escucha'
      path: '/escucha'
      fullPath: '/escucha'
      preLoaderRoute: typeof EscuchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diccionario': {
      id: '/diccionario'
      path: '/diccionario'
      fullPath: '/diccionario'
      preLoaderRoute: typeof DiccionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultura': {
      id: '/cultura'
      path: '/cultura'
      fullPath: '/cultura'
      preLoaderRoute: typeof CulturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribuir': {
      id: '/contribuir'
      path: '/contribuir'
      fullPath: '/contribuir'
      preLoaderRoute: typeof ContribuirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprende': {
      id: '/aprende'
      path: '/aprende'
      fullPath: '/aprende'
      preLoaderRoute: typeof AprendeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/': {
      id: '/juegos/'
      path: '/'
      fullPath: '/juegos/'
      preLoaderRoute: typeof JuegosIndexRouteImport
      parentRoute: typeof JuegosRoute
    }
    '/juegos/sopa': {
      id: '/juegos/sopa'
      path: '/sopa'
      fullPath: '/juegos/sopa'
      preLoaderRoute: typeof JuegosSopaRouteImport
      parentRoute: typeof JuegosRoute
    }
    '/juegos/quiz': {
      id: '/juegos/quiz'
      path: '/quiz'
      fullPath: '/juegos/quiz'
      preLoaderRoute: typeof JuegosQuizRouteImport
      parentRoute: typeof JuegosRoute
    }
    '/juegos/memorama': {
      id: '/juegos/memorama'
      path: '/memorama'
      fullPath: '/juegos/memorama'
      preLoaderRoute: typeof JuegosMemoramaRouteImport
      parentRoute: typeof JuegosRoute
    }
    '/juegos/flasgcards': {
      id: '/juegos/flasgcards'
      path: '/flasgcards'
      fullPath: '/juegos/flasgcards'
      preLoaderRoute: typeof JuegosFlasgcardsRouteImport
      parentRoute: typeof JuegosRoute
    }
    '/aprende/$slug': {
      id: '/aprende/$slug'
      path: '/$slug'
      fullPath: '/aprende/$slug'
      preLoaderRoute: typeof AprendeSlugRouteImport
      parentRoute: typeof AprendeRoute
    }
  }
}

interface AprendeRouteChildren {
  AprendeSlugRoute: typeof AprendeSlugRoute
}

const AprendeRouteChildren: AprendeRouteChildren = {
  AprendeSlugRoute: AprendeSlugRoute,
}

const AprendeRouteWithChildren =
  AprendeRoute._addFileChildren(AprendeRouteChildren)

interface JuegosRouteChildren {
  JuegosFlasgcardsRoute: typeof JuegosFlasgcardsRoute
  JuegosMemoramaRoute: typeof JuegosMemoramaRoute
  JuegosQuizRoute: typeof JuegosQuizRoute
  JuegosSopaRoute: typeof JuegosSopaRoute
  JuegosIndexRoute: typeof JuegosIndexRoute
}

const JuegosRouteChildren: JuegosRouteChildren = {
  JuegosFlasgcardsRoute: JuegosFlasgcardsRoute,
  JuegosMemoramaRoute: JuegosMemoramaRoute,
  JuegosQuizRoute: JuegosQuizRoute,
  JuegosSopaRoute: JuegosSopaRoute,
  JuegosIndexRoute: JuegosIndexRoute,
}

const JuegosRouteWithChildren =
  JuegosRoute._addFileChildren(JuegosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprendeRoute: AprendeRouteWithChildren,
  ContribuirRoute: ContribuirRoute,
  CulturaRoute: CulturaRoute,
  DiccionarioRoute: DiccionarioRoute,
  EscuchaRoute: EscuchaRoute,
  JuegosRoute: JuegosRouteWithChildren,
  LoginRoute: LoginRoute,
  PalabraDelDiaRoute: PalabraDelDiaRoute,
  RelatosRoute: RelatosRoute,
  VocabularioRoute: VocabularioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
